#!/usr/bin/bash
set -e # exit on error
temp=`mktemp -d`

cd $1
tar -hcvf - . | xz -9ec > $temp/archive.tar.xz
clear
cd -
gpg -z 0 --symmetric --cipher-algo AES256 -a -o Data.gpg $temp/archive.tar.xz
rm -rf $temp
